# Generated by Django 6.1.1 on 2026-09-26 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("origen", models.CharField(max_length=200)),
                ("destino", models.CharField(max_length=200)),
                ("peso_kg", models.FloatField(default=1.0)),
                ("distancia_km", models.FloatField(default=10.0)),
                ("urgente", models.BooleanField(default=False)),
                ("estado", models.CharField(default="Registrado", max_length=50)),
                ("eta", models.CharField(default="Pendiente", max_length=50)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
